OG612: fix relayTransaction response processing in browser
the current code in `RelayedTransactionValidator` was node-specifc,
where BN type has "toBuffer", which is not true in chrome.

As a result, sending a transaciton returns an error:
"transaction.v.toBuffer is not a function"

(even though the underlying transaction succeeded, but you need to
"Refersh" the page to see its side-effect.)

Modified the code to support both node and browser